apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-second
  labels:
    app: e-second
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-second
  template:
    metadata:
      labels:
        app: e-second
    spec:
      containers:
      - name: e-second
        image: maheshmu/e-second:latest
        ports:
        - containerPort: 8095
---
apiVersion: v1
kind: Service
metadata:
  name: e-second
spec:
  type: LoadBalancer
  selector:
    app: e-second
  ports:
    - port: 8096
      targetPort: 8095
 
